'use client'

import { useState } from 'react'
import { BadgeCheck, CheckCircle2, ShieldCheck, KeyRound, Camera, Signature, Package } from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { toast } from 'sonner'

export default function DigitalProofOfDeliveryPage() {
  const [shipmentId, setShipmentId] = useState('SHP-TZ-9021')
  const [customerOtp, setCustomerOtp] = useState('')
  const [recipientName, setRecipientName] = useState('')
  const [isVerified, setIsVerified] = useState(false)

  function handleVerifyOtp(e: React.FormEvent) {
    e.preventDefault()
    if (!customerOtp.trim()) {
      toast.error('Please enter the 6-digit customer OTP')
      return
    }
    if (customerOtp.trim() !== '882910' && customerOtp.length !== 6) {
      toast.error('Invalid delivery OTP code')
      return
    }

    setIsVerified(true)
    toast.success('Customer OTP Verified! Electronic Proof of Delivery (e-POD) signed!')
  }

  return (
    <div className="flex flex-col gap-6">
      <div>
        <h1 className="text-2xl font-extrabold tracking-tight">Digital Proof of Delivery (e-POD)</h1>
        <p className="text-sm text-muted-foreground">
          Validate customer OTP confirmation codes, digital signatures, and cargo drop-off photo proof.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* OTP Delivery Verification Card */}
        <Card>
          <CardHeader>
            <CardTitle className="text-base font-extrabold flex items-center gap-2">
              <BadgeCheck className="size-5 text-emerald-500" />
              OTP Handover Verification
            </CardTitle>
            <CardDescription className="text-xs">
              Drivers must input the SMS OTP generated by the customer to release protected funds to supplier.
            </CardDescription>
          </CardHeader>

          <CardContent>
            {isVerified ? (
              <div className="bg-emerald-500/10 border border-emerald-500/30 rounded-xl p-6 text-center space-y-3">
                <CheckCircle2 className="size-12 text-emerald-500 mx-auto" />
                <div>
                  <h3 className="text-base font-extrabold text-foreground">Delivery Signed &amp; Trade Protection Released!</h3>
                  <p className="text-xs text-muted-foreground mt-1">
                    Shipment <strong className="text-foreground">{shipmentId}</strong> has been handed over to <strong className="text-foreground">{recipientName || 'Juma Mkwawa'}</strong>.
                  </p>
                </div>
                <Button
                  onClick={() => setIsVerified(false)}
                  variant="outline"
                  size="sm"
                  className="text-xs font-bold"
                >
                  Sign Another Handover
                </Button>
              </div>
            ) : (
              <form onSubmit={handleVerifyOtp} className="space-y-4 text-xs">
                <div className="space-y-1">
                  <label className="font-bold">Shipment Manifest ID</label>
                  <Input
                    value={shipmentId}
                    onChange={(e) => setShipmentId(e.target.value)}
                    className="text-xs font-mono uppercase"
                  />
                </div>

                <div className="space-y-1">
                  <label className="font-bold">Recipient Full Name</label>
                  <Input
                    placeholder="e.g. Juma Mkwawa (Store Manager)"
                    value={recipientName}
                    onChange={(e) => setRecipientName(e.target.value)}
                    className="text-xs"
                  />
                </div>

                <div className="space-y-1">
                  <label className="font-bold flex items-center justify-between">
                    <span>Customer 6-Digit SMS OTP</span>
                    <span className="text-[10px] text-muted-foreground font-mono font-normal">Demo OTP: 882910</span>
                  </label>
                  <Input
                    placeholder="Enter 6-digit OTP code"
                    value={customerOtp}
                    onChange={(e) => setCustomerOtp(e.target.value)}
                    maxLength={6}
                    className="text-xs font-mono text-center text-lg tracking-widest"
                  />
                </div>

                <Button type="submit" className="w-full bg-emerald-600 hover:bg-emerald-700 text-white font-bold text-xs">
                  <ShieldCheck className="size-4 mr-1.5" />
                  Confirm Delivery &amp; Sign POD
                </Button>
              </form>
            )}
          </CardContent>
        </Card>

        {/* Photo Proof & Signature Card */}
        <Card>
          <CardHeader>
            <CardTitle className="text-base font-extrabold flex items-center gap-2">
              <Camera className="size-5 text-brand-500" />
              Cargo Photo Proof &amp; Signatures
            </CardTitle>
            <CardDescription className="text-xs">
              Upload drop-off photo evidence showing intact security seal.
            </CardDescription>
          </CardHeader>

          <CardContent className="space-y-4">
            <div className="border-2 border-dashed rounded-xl p-6 flex flex-col items-center justify-center text-center space-y-2 bg-muted/20 cursor-pointer">
              <Camera className="size-8 text-brand-500" />
              <p className="text-xs font-bold text-foreground">Click to upload cargo photo proof</p>
              <p className="text-[10px] text-muted-foreground">High resolution PNG, JPG taken at customer dock</p>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}
